apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1

    datasources:
      - name: Osiks Datasource
        type: yesoreyeram-infinity-datasource
  plugins.yaml: |
    apiVersion: 1
    
    apps:
      - name: Osiks Infinity
        type: yesoreyeram-infinity-datasource
  dashboards.yaml: |
    apiVersion: 1
    
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: true
  lab-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "linear",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "maxHeight": 600,
              "mode": "single",
              "sort": "none"
            }
          },
          "targets": [
            {
              "datasource": {
                "type": "datasource",
                "uid": "grafana"
              },
              "queryType": "randomWalk",
              "refId": "A"
            }
          ],
          "title": "Panel Title",
          "type": "timeseries"
        }
      ],
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timeRangeUpdatedDuringEditOrView": false,
      "timepicker": {},
      "timezone": "browser",
      "title": "Osiks dashboard",
      "uid": "bdpn84tlzki68b",
      "version": 1,
      "weekStart": ""
    }
  health-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 2,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "yesoreyeram-infinity-datasource",
            "uid": "P0BE9604242393BD2"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [
                {
                  "options": {
                    "Healthy": {
                      "color": "green",
                      "index": 0
                    },
                    "Unhealthy": {
                      "color": "red",
                      "index": 1
                    }
                  },
                  "type": "value"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "infinitePan": false,
            "inlineEditing": true,
            "panZoom": false,
            "root": {
              "background": {
                "color": {
                  "fixed": "transparent"
                }
              },
              "border": {
                "color": {
                  "fixed": "dark-green"
                }
              },
              "constraint": {
                "horizontal": "left",
                "vertical": "top"
              },
              "elements": [
                {
                  "background": {
                    "color": {
                      "field": "Status",
                      "fixed": "#D9D9D9"
                    }
                  },
                  "border": {
                    "color": {
                      "fixed": "dark-green"
                    }
                  },
                  "config": {
                    "align": "center",
                    "color": {
                      "fixed": "#000000"
                    },
                    "text": {
                      "field": "Status",
                      "mode": "field"
                    },
                    "valign": "middle"
                  },
                  "constraint": {
                    "horizontal": "left",
                    "vertical": "top"
                  },
                  "name": "Element 1",
                  "placement": {
                    "height": 200,
                    "left": 400,
                    "top": 20,
                    "width": 200
                  },
                  "type": "ellipse"
                }
              ],
              "name": "Element 1719164894802",
              "placement": {
                "height": 100,
                "left": 0,
                "rotation": 0,
                "top": 0,
                "width": 100
              },
              "type": "frame"
            },
            "showAdvancedTypes": true
          },
          "pluginVersion": "11.0.0",
          "targets": [
            {
              "columns": [
                {
                  "selector": "status",
                  "text": "Status",
                  "type": "string"
                }
              ],
              "datasource": {
                "type": "yesoreyeram-infinity-datasource",
                "uid": "P0BE9604242393BD2"
              },
              "filters": [],
              "format": "table",
              "global_query_id": "",
              "refId": "A",
              "root_selector": "$",
              "source": "url",
              "type": "json",
              "url": "http://nginx.osiks-nginx.svc:8083/health.json",
              "url_options": {
                "data": "",
                "method": "GET"
              }
            }
          ],
          "title": "Service",
          "type": "canvas"
        }
      ],
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timeRangeUpdatedDuringEditOrView": false,
      "timepicker": {},
      "timezone": "browser",
      "title": "Health",
      "uid": "edpo218hry5mof",
      "version": 2,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  name: osiks-grafana-cm
