apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: prometheus
  name: prometheus
spec:
  containers:
  - image: quay.io/prometheus/prometheus
    name: prometheus
    volumeMounts:
      - name: config-volume
        mountPath: /etc/prometheus
    resources: {}
  volumes:
    - name: config-volume
      configMap:
        name: prometheus
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
