apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: osiks-nginx
    run: nginx
  name: nginx
  namespace: osiks-nginx
spec:
  ports:
  - nodePort: 30003
    port: 8083
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: osiks-nginx
    run: nginx
  type: NodePort
