apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: osiks-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: health-vol
      mountPath: "/usr/share/nginx/html/health.json"
      subPath: health.json
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: health-vol
    configMap:
      name: osiks-nginx
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: osiks-nginx
