apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pebble-issuer
  namespace: kuard
spec:
  acme:
    # The ACME server URL
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://pebble.pebble/dir
    # Email address used for ACME registration
    email: user@example.com
    # Name of secret used to store the ACME account private key
    privateKeySecretRef:
      name: pebble
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
    skipTLSVerify: true
