# Pebble's Helm chart configuration (my-values.yaml)
coredns:
  # make all DNS lookups to "test" and subdomains go to the
  # Kubernetes service named mysvc in the same namespaces as
  # Pebble is installed
  corefileSegment: |-
    template ANY ANY test {
      #answer "{{ .Name }} 60 IN CNAME nginx.{$PEBBLE_NAMESPACE}.svc.cluster.local"
      answer "{{ .Name }} 60 IN CNAME kuard.kuard.svc.cluster.local"
    }
