apiVersion: v1
data:
  Corefile: |-
    .:8053 {
      errors
      health
      ready
      template ANY ANY kuard {
        answer "{{ .Name }} 60 IN CNAME nginx.{$PEBBLE_NAMESPACE}.svc.cluster.local"
      }
      forward . /etc/resolv.conf
      cache 2
      reload
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: pebble
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-07-01T09:11:34Z"
  labels:
    app.kubernetes.io/instance: pebble
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pebble-coredns
    app.kubernetes.io/version: 2.5.1
    helm.sh/chart: pebble-1.1.0
  name: pebble-coredns
  namespace: default
  resourceVersion: "24619"
  uid: 7b9471f1-d369-4f6d-bda4-52b003a07e98
