apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: nginx
spec:
  containers:
  - image: nginx
    name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30008
  selector:
    run: nginx
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    cert-manager.io/cluster-issuer: pebble
  namespace: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - osiks.local
    secretName: osiks-local-tls
  rules:
    - host: osiks.local
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx
                port:
                  number: 80
---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: pebble
#  namespace: nginx
#spec:
#  acme:
#    skipTLSVerify: true
#    email: user-nginx@osiks.com
#    server: https://pebble.pebble/dir
#    privateKeySecretRef:
#      name: pebble-account-private-key
#    solvers:
#      - http01:
#          ingress:
#            ingressClassName: nginx
