apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pebble
  namespace: nginx
spec:
  acme:
    skipTLSVerify: true
    email: user-nginx@osiks.com
    server: https://pebble.pebble/dir
    privateKeySecretRef:
      name: pebble-account-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
